using Bromine.Playwright.Extensions.Configuration;
using Microsoft.Playwright;

namespace Bromine.Playwright.Extensions.Extensions;

/// <summary>
/// Extension methods for <see cref="ILocator"/> providing aria snapshot and
/// locator-normalisation helpers.
/// </summary>
public static class LocatorExtensions
{
    /// <summary>
    /// Capture the aria snapshot of the matched element.
    /// <para>
    /// <paramref name="depth"/> is passed through, but note that Playwright 1.59 only honours it
    /// for page-level <see cref="AriaSnapshotMode.Ai"/> snapshots — it had no observable effect
    /// on locator snapshots in either mode. Requires Playwright 1.59 or newer.
    /// </para>
    /// </summary>
    public static async Task<string> GetAriaSnapshotAsync(
        this ILocator locator,
        int? depth = null,
        AriaSnapshotMode? mode = null,
        float? timeoutMs = null)
    {
        return await locator.AriaSnapshotAsync(new LocatorAriaSnapshotOptions
        {
            Depth = depth,
            Mode = mode,
            Timeout = timeoutMs ?? PlaywrightDefaults.ActionTimeout
        });
    }

    /// <summary>
    /// Capture the aria snapshot of the matched element in the AI-optimised shape
    /// (<see cref="AriaSnapshotMode.Ai"/>), for handing element structure to a model.
    /// </summary>
    public static Task<string> GetAriaSnapshotForAiAsync(
        this ILocator locator,
        int? depth = null,
        float? timeoutMs = null)
        => locator.GetAriaSnapshotAsync(depth, AriaSnapshotMode.Ai, timeoutMs);

    /// <summary>
    /// Rewrite this locator to follow Playwright's recommended practices — test ids and aria
    /// roles ahead of CSS — and return the selector it resolves to.
    /// <para>
    /// Handy for logging or for migrating a brittle CSS selector: point it at an element, print
    /// what comes back, and paste that into the test. Requires Playwright 1.59 or newer.
    /// </para>
    /// </summary>
    public static async Task<string> NormalizedSelectorAsync(this ILocator locator)
    {
        var normalized = await locator.NormalizeAsync();

        // ToString() is annotated nullable on object; Playwright's locators always render a
        // selector, so an empty string is a safer contract here than handing back null.
        return normalized.ToString() ?? string.Empty;
    }

    /// <summary>
    /// Drop files onto this element, as if they had been dragged in from the desktop.
    /// <para>
    /// Distinct from <c>SetInputFilesAsync</c>: that drives a file input directly, whereas this
    /// fires real drag-and-drop events at a drop zone, which is the only way to exercise a
    /// dropzone that has no <c>&lt;input type="file"&gt;</c> behind it.
    /// Requires Playwright 1.60 or newer.
    /// </para>
    /// </summary>
    public static Task DropFilesAsync(
        this ILocator locator,
        IEnumerable<string> filePaths,
        Position? position = null,
        float? timeoutMs = null)
    {
        return locator.DropAsync(
            new DropPayload { FilePaths = filePaths },
            DropOptions(position, timeoutMs));
    }

    /// <summary>
    /// Drop in-memory files onto this element, without touching the filesystem.
    /// Useful when the content is generated by the test. Requires Playwright 1.60 or newer.
    /// </summary>
    public static Task DropFilesAsync(
        this ILocator locator,
        IEnumerable<FilePayload> files,
        Position? position = null,
        float? timeoutMs = null)
    {
        return locator.DropAsync(
            new DropPayload { Files = files },
            DropOptions(position, timeoutMs));
    }

    /// <summary>
    /// Drop raw data onto this element, keyed by MIME type — e.g. <c>text/plain</c> or
    /// <c>text/uri-list</c> — as a real drag-and-drop would carry it.
    /// Requires Playwright 1.60 or newer.
    /// </summary>
    public static Task DropDataAsync(
        this ILocator locator,
        IEnumerable<KeyValuePair<string, string>> data,
        Position? position = null,
        float? timeoutMs = null)
    {
        return locator.DropAsync(
            new DropPayload { Data = data },
            DropOptions(position, timeoutMs));
    }

    /// <summary>
    /// Drop a single <c>text/plain</c> payload onto this element.
    /// </summary>
    public static Task DropTextAsync(
        this ILocator locator,
        string text,
        Position? position = null,
        float? timeoutMs = null)
        => locator.DropDataAsync([new KeyValuePair<string, string>("text/plain", text)], position, timeoutMs);

    /// <summary>
    /// Outline this element, run <paramref name="action"/>, then remove the outline — so a
    /// screenshot or screencast taken during the action shows what it was acting on.
    /// <para>
    /// A working scope, which the raw API does not give you: <c>HighlightAsync</c> returns an
    /// <see cref="IAsyncDisposable"/> in Playwright 1.60, but the value is a no-op stub, so
    /// <c>await using</c> would leave the highlight on. The outline is removed even if the action
    /// throws. Requires Playwright 1.60 or newer.
    /// </para>
    /// </summary>
    public static async Task HighlightWhileAsync(
        this ILocator locator,
        Func<Task> action,
        string? style = null)
    {
        _ = await locator.HighlightAsync(new LocatorHighlightOptions { Style = style });
        try
        {
            await action();
        }
        finally
        {
            await locator.HideHighlightAsync();
        }
    }

    private static LocatorDropOptions? DropOptions(Position? position, float? timeoutMs)
    {
        if (position is null && timeoutMs is null)
            return null;

        var options = new LocatorDropOptions { Timeout = timeoutMs ?? PlaywrightDefaults.ActionTimeout };
        if (position is not null)
            options.Position = position;

        return options;
    }
}
